 project:
  type: website
  output-dir: docs

website:
  title: "M10: Hands-on Practice Assignment"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: dashboard.qmd
        text: Dashboard
      - href: shiny-apps.qmd
        text: Essay on Shiny Apps
      - href: shiny-live.qmd
        text: Essay on Shiny Live

format:
  html:
    theme: cosmo
    toc: true
